// Nội dung cho widget "Gợi ý hôm nay" và "Nghỉ 5 phút".
// Muốn thêm câu mới: thêm vào mảng tương ứng rồi tạo PR.
window.FUN_DATA = {
  quotes: [
    'Việc hôm nay chớ để ngày mai.',
    'Đi một ngày đàng, học một sàng khôn.',
    'Có công mài sắt, có ngày nên kim.',
    'Muốn đi nhanh thì đi một mình, muốn đi xa thì đi cùng nhau.',
    'Thất bại là mẹ thành công.',
    'Học, học nữa, học mãi.',
    'Không có việc gì khó, chỉ sợ lòng không bền.',
    'Một cây làm chẳng nên non, ba cây chụm lại nên hòn núi cao.',
    'Cách tốt nhất để dự đoán tương lai là tạo ra nó.',
    'Hoàn thành tốt hơn hoàn hảo.',
    'Đơn giản là đỉnh cao của tinh tế.',
    'Người giỏi không phải là người làm tất cả, mà là người biết giao đúng việc cho đúng người.',
    'Chậm mà chắc.',
    'Sai một ly, đi một dặm — đo hai lần, cắt một lần.',
    'Kiến tha lâu cũng đầy tổ.',
    'Nếu bạn không thể giải thích đơn giản, nghĩa là bạn chưa hiểu đủ sâu.',
    'Đừng đếm những gì bạn đã mất, hãy quý những gì bạn đang có.',
    'Mỗi ngày tốt hơn 1% — một năm tốt hơn 37 lần.',
    'Việc lớn bắt đầu từ việc nhỏ.',
    'Hỏi một câu chỉ dốt trong chốc lát, không hỏi sẽ dốt cả đời.'
  ],
  tips: [
    'Trước khi restart thiết bị, hãy lưu lại log — restart xong là mất dấu vết sự cố.',
    'Đặt tên file có ngày tháng dạng YYYY-MM-DD để sắp xếp tự động đúng thứ tự.',
    'Ctrl+Shift+V dán văn bản không kèm định dạng — đỡ phải xoá format thủ công.',
    'Kiểm tra backup định kỳ bằng cách thử restore — backup chưa restore thử là backup chưa chắc dùng được.',
    'Viết email xong, đọc lại một lần bằng con mắt của người nhận trước khi gửi.',
    'Sự cố lặp lại 2 lần thì lần thứ 3 nên có quy trình xử lý viết sẵn.',
    'Windows + V mở lịch sử clipboard — dán lại thứ đã copy trước đó.',
    'Đừng tin "chắc là được" — hãy test trên môi trường thật trước giờ cao điểm.',
    'Ghi chú ngay sau cuộc họp 5 phút, đừng đợi cuối ngày — não quên nhanh hơn bạn nghĩ.',
    'Password dài dễ nhớ an toàn hơn password ngắn phức tạp.',
    'Trước khi thay đổi cấu hình, chụp/lưu lại cấu hình cũ để rollback nhanh.',
    'Một việc mất dưới 2 phút thì làm luôn, đừng cho vào danh sách chờ.',
    'Ctrl+Shift+T mở lại tab trình duyệt vừa đóng nhầm.',
    'Báo cáo sự cố tốt gồm: hiện tượng, thời điểm, phạm vi ảnh hưởng, đã thử gì.',
    'Đặt lịch họp 25/50 phút thay vì 30/60 — chừa thời gian di chuyển giữa các cuộc họp.',
    'Tài liệu tốt nhất là tài liệu viết ngay khi vừa làm xong, còn nhớ rõ chi tiết.',
    'Kiểm tra kỹ người nhận trước khi bấm Reply All.',
    'Việc gấp chưa chắc quan trọng, việc quan trọng chưa chắc gấp — ưu tiên theo cả hai chiều.',
    'Windows + Shift + S chụp nhanh một vùng màn hình.',
    'Khi bàn giao việc, bàn giao cả "vì sao làm thế" chứ không chỉ "làm thế nào".'
  ],
  hacks: [
    'Uống một cốc nước ngay khi ngồi vào bàn làm việc.',
    'Quy tắc 20-20-20: mỗi 20 phút nhìn xa 20 feet (6m) trong 20 giây cho đỡ mỏi mắt.',
    'Đứng dậy vươn vai mỗi khi gửi xong một báo cáo.',
    'Việc khó nhất làm đầu tiên vào buổi sáng, lúc đầu óc còn tỉnh táo.',
    'Tắt thông báo 45 phút khi cần tập trung sâu.',
    'Để cây xanh nhỏ trên bàn — mắt được nghỉ, tinh thần dễ chịu hơn.',
    'Trước khi về, viết 3 việc cần làm đầu tiên sáng mai.',
    'Đi cầu thang bộ thay thang máy nếu chỉ 1-2 tầng.',
    'Ăn trưa xa màn hình máy tính — não cũng cần giờ nghỉ trưa.',
    'Sắp xếp bàn làm việc 2 phút cuối ngày, sáng mai vào việc nhanh hơn.',
    'Hít thở sâu 4 nhịp trước khi trả lời một tin nhắn khiến bạn bực mình.',
    'Đặt chai nước trong tầm mắt — nhìn thấy là nhớ uống.',
    'Nghe một bản nhạc không lời khi làm việc lặp đi lặp lại.',
    'Chỉnh màn hình ngang tầm mắt để đỡ mỏi cổ.',
    'Nghỉ 5 phút sau mỗi 50 phút làm việc — năng suất tổng cao hơn làm liền 3 tiếng.',
    'Đi bộ ra cửa sổ nhìn trời 1 phút khi thấy bí ý tưởng.',
    'Gõ phím nhẹ tay thôi — cổ tay sẽ cảm ơn bạn sau 10 năm nữa.',
    'Cười với đồng nghiệp buổi sáng — miễn phí mà hiệu quả cả ngày.',
    'Chớp mắt chậm 10 lần khi mắt khô vì nhìn màn hình lâu.',
    'Đừng ăn trưa quá no nếu chiều có cuộc họp quan trọng.'
  ],
  // "Món quà" mỗi ngày: xen kẽ kiến thức hay / bài nhạc / món ăn nhẹ cho bữa trưa
  extras: [
    {tag:'🎵 Nhạc hay', text:'“Ngày chưa giông bão” — Bùi Lan Hương. Nhẹ nhàng cho một buổi làm việc tập trung.'},
    {tag:'📚 Bạn có biết', text:'Cáp quang biển truyền ~99% lưu lượng internet quốc tế — sóng vệ tinh chỉ là phần rất nhỏ.'},
    {tag:'🍜 Bữa trưa nhẹ', text:'Bún chả + chút rau sống — đủ năng lượng mà chiều không buồn ngủ.'},
    {tag:'🎵 Nhạc hay', text:'“Clair de Lune” — Debussy. Nhạc không lời, hợp lúc cần nghĩ sâu.'},
    {tag:'📚 Bạn có biết', text:'Chuẩn giờ của mạng viễn thông đồng bộ tới phần triệu giây — lệch nhỏ là rớt cuộc gọi.'},
    {tag:'🍜 Bữa trưa nhẹ', text:'Cơm gà xé + canh rau — nhanh gọn, đạm đủ cho buổi chiều họp hành.'},
    {tag:'🎵 Nhạc hay', text:'“Fly Me to the Moon” — Frank Sinatra. Jazz nhẹ cho giờ nghỉ trưa.'},
    {tag:'📚 Bạn có biết', text:'Mật khẩu 12 ký tự ngẫu nhiên mất hàng trăm năm để dò — 8 ký tự chỉ vài giờ.'},
    {tag:'🍜 Bữa trưa nhẹ', text:'Phở gà + trà đá — combo kinh điển không bao giờ sai.'},
    {tag:'🎵 Nhạc hay', text:'“Mưa rơi lặng thầm” — Trung Quân. Hợp những chiều mưa nhìn ra cửa sổ.'},
    {tag:'📚 Bạn có biết', text:'Não người xử lý hình ảnh nhanh gấp ~60.000 lần chữ viết — vì thế dashboard trực quan luôn thắng báo cáo dài.'},
    {tag:'🍜 Bữa trưa nhẹ', text:'Bánh mì trứng + sữa chua hoa quả — gọn nhẹ cho ngày bận.'},
    {tag:'🎵 Nhạc hay', text:'“River Flows in You” — Yiruma. Piano dịu cho lúc cần bình tĩnh xử lý sự cố.'},
    {tag:'📚 Bạn có biết', text:'Quy tắc 1-10-100: lỗi phát hiện lúc thiết kế tốn 1 đồng, lúc triển khai 10 đồng, khi vận hành 100 đồng.'},
    {tag:'🍜 Bữa trưa nhẹ', text:'Bún riêu + rau muống chẻ — chua nhẹ, chống ngán giữa tuần.'},
    {tag:'🎵 Nhạc hay', text:'“Có chàng trai viết lên cây” — Phan Mạnh Quỳnh. Nghe lúc nghỉ trưa cho thư thả.'},
    {tag:'📚 Bạn có biết', text:'80% sự cố mạng nghiêm trọng bắt nguồn từ thay đổi cấu hình — vì thế mới cần quy trình change management.'},
    {tag:'🍜 Bữa trưa nhẹ', text:'Cháo sườn + quẩy — ấm bụng cho những hôm trở trời.'},
    {tag:'🎵 Nhạc hay', text:'“Lofi chill Việt” — playlist không lời, bật nhỏ làm nền cả buổi chiều.'},
    {tag:'📚 Bạn có biết', text:'Tháp truyền hình cao nhất Việt Nam ở Hà Nội cao 250m — nhưng trạm BTS chỉ cần 30–70m là phủ tốt một khu dân cư.'}
  ],
  quiz: [
    {q:'Cái gì càng lấy đi càng to ra?', a:'Cái hố'},
    {q:'Con gì đầu dê mình ốc?', a:'Con dốc'},
    {q:'Cái gì luôn đi tới mà không bao giờ đi lui?', a:'Thời gian'},
    {q:'Cái gì của bạn nhưng người khác dùng nhiều hơn bạn?', a:'Tên của bạn'},
    {q:'Con gì càng to càng nhỏ?', a:'Con cua (càng to, càng nhỏ)'},
    {q:'Cái gì có 4 chân buổi sáng, 2 chân buổi trưa, 3 chân buổi tối?', a:'Con người (bò → đi → chống gậy)'},
    {q:'Cái gì đen khi mua, đỏ khi dùng, xám khi vứt đi?', a:'Than'},
    {q:'Núi nào mà bị chặt ra từng khúc?', a:'Thái Sơn (thái = chặt nhỏ)'},
    {q:'Cái gì càng phơi càng ướt?', a:'Cái lưỡi (phơi ra khỏi miệng)'},
    {q:'Bỏ ngoài nướng trong, ăn ngoài bỏ trong là gì?', a:'Bắp ngô'},
    {q:'Cái gì có cổ nhưng không có đầu?', a:'Cái áo'},
    {q:'Con đường nào dài nhất?', a:'Đường đời'},
    {q:'Cái gì đi thì nằm, đứng cũng nằm, nhưng nằm lại đứng?', a:'Bàn chân'},
    {q:'Có 1 đàn chim đậu trên cành, người thợ săn bắn rơi 1 con. Hỏi còn mấy con?', a:'0 con — nghe tiếng súng bay hết'},
    {q:'Cái gì bạn không muốn có, nhưng có rồi lại không muốn mất?', a:'Vụ kiện (mất kiện là thua!)'},
    {q:'2 người đào 2 cái hố hết 2 giờ. Hỏi 1 người đào 1 cái hố hết mấy giờ?', a:'2 giờ'},
    {q:'Cái gì tay trái cầm được, tay phải không cầm được?', a:'Cùi chỏ tay phải'},
    {q:'Tháng nào có 28 ngày?', a:'Tháng nào cũng có (ít nhất) 28 ngày'},
    {q:'Vừa bằng cái vung, vùng xuống ao, đào chẳng thấy, lấy chẳng được — là cái gì?', a:'Mặt trăng (bóng trăng dưới nước)'},
    {q:'Vừa bằng hạt đỗ, ăn giỗ cả làng — là con gì?', a:'Con ruồi'}
  ],
  reminders: [
    '🚶 Đứng dậy đi bộ 5 phút cho giãn gân cốt nào!',
    '💧 Uống nước chưa đó? Làm một cốc đi!',
    '👀 Nhìn ra xa 20 giây cho mắt nghỉ nhé.',
    '🙆 Vươn vai, xoay cổ một vòng nào!',
    '🌤️ Ra cửa sổ hít thở không khí một chút đi.',
    '☕ Pha một ly trà/cà phê, thư giãn 5 phút.',
    '🧘 Hít sâu, thở chậm 5 nhịp — reset não bộ.',
    '🤝 Quay sang hỏi thăm đồng nghiệp một câu nào!'
  ]
};
